// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pbf/metrics/api.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pbf_metrics_api_proto protoreflect.FileDescriptor

const file_pbf_metrics_api_proto_rawDesc = "" +
	"\n" +
	"\x15pbf/metrics/api.proto\x12\ametrics\x1a\x19pbf/metrics/counter.proto\x1a\x17pbf/metrics/gauge.proto\x1a\x1bpbf/metrics/histogram.proto2\x9e\x01\n" +
	"\x03API\x121\n" +
	"\aCounter\x12\x11.metrics.CounterI\x1a\x11.metrics.CounterO\"\x00\x12+\n" +
	"\x05Gauge\x12\x0f.metrics.GaugeI\x1a\x0f.metrics.GaugeO\"\x00\x127\n" +
	"\tHistogram\x12\x13.metrics.HistogramI\x1a\x13.metrics.HistogramO\"\x00B\fZ\n" +
	"./;metricsb\x06proto3"

var file_pbf_metrics_api_proto_goTypes = []any{
	(*CounterI)(nil),   // 0: metrics.CounterI
	(*GaugeI)(nil),     // 1: metrics.GaugeI
	(*HistogramI)(nil), // 2: metrics.HistogramI
	(*CounterO)(nil),   // 3: metrics.CounterO
	(*GaugeO)(nil),     // 4: metrics.GaugeO
	(*HistogramO)(nil), // 5: metrics.HistogramO
}
var file_pbf_metrics_api_proto_depIdxs = []int32{
	0, // 0: metrics.API.Counter:input_type -> metrics.CounterI
	1, // 1: metrics.API.Gauge:input_type -> metrics.GaugeI
	2, // 2: metrics.API.Histogram:input_type -> metrics.HistogramI
	3, // 3: metrics.API.Counter:output_type -> metrics.CounterO
	4, // 4: metrics.API.Gauge:output_type -> metrics.GaugeO
	5, // 5: metrics.API.Histogram:output_type -> metrics.HistogramO
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbf_metrics_api_proto_init() }
func file_pbf_metrics_api_proto_init() {
	if File_pbf_metrics_api_proto != nil {
		return
	}
	file_pbf_metrics_counter_proto_init()
	file_pbf_metrics_gauge_proto_init()
	file_pbf_metrics_histogram_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbf_metrics_api_proto_rawDesc), len(file_pbf_metrics_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbf_metrics_api_proto_goTypes,
		DependencyIndexes: file_pbf_metrics_api_proto_depIdxs,
	}.Build()
	File_pbf_metrics_api_proto = out.File
	file_pbf_metrics_api_proto_goTypes = nil
	file_pbf_metrics_api_proto_depIdxs = nil
}
