// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pbf/metrics/histogram.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HistogramI is the input for updating histograms.
type HistogramI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        []*Action              `protobuf:"bytes,100,rep,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramI) Reset() {
	*x = HistogramI{}
	mi := &file_pbf_metrics_histogram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramI) ProtoMessage() {}

func (x *HistogramI) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_metrics_histogram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramI.ProtoReflect.Descriptor instead.
func (*HistogramI) Descriptor() ([]byte, []int) {
	return file_pbf_metrics_histogram_proto_rawDescGZIP(), []int{0}
}

func (x *HistogramI) GetAction() []*Action {
	if x != nil {
		return x.Action
	}
	return nil
}

// HistogramO is the output for updating histograms.
type HistogramO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*Result              `protobuf:"bytes,100,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramO) Reset() {
	*x = HistogramO{}
	mi := &file_pbf_metrics_histogram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramO) ProtoMessage() {}

func (x *HistogramO) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_metrics_histogram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramO.ProtoReflect.Descriptor instead.
func (*HistogramO) Descriptor() ([]byte, []int) {
	return file_pbf_metrics_histogram_proto_rawDescGZIP(), []int{1}
}

func (x *HistogramO) GetResult() []*Result {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_pbf_metrics_histogram_proto protoreflect.FileDescriptor

const file_pbf_metrics_histogram_proto_rawDesc = "" +
	"\n" +
	"\x1bpbf/metrics/histogram.proto\x12\ametrics\x1a\x18pbf/metrics/common.proto\"5\n" +
	"\n" +
	"HistogramI\x12'\n" +
	"\x06action\x18d \x03(\v2\x0f.metrics.ActionR\x06action\"5\n" +
	"\n" +
	"HistogramO\x12'\n" +
	"\x06result\x18d \x03(\v2\x0f.metrics.ResultR\x06resultB\fZ\n" +
	"./;metricsb\x06proto3"

var (
	file_pbf_metrics_histogram_proto_rawDescOnce sync.Once
	file_pbf_metrics_histogram_proto_rawDescData []byte
)

func file_pbf_metrics_histogram_proto_rawDescGZIP() []byte {
	file_pbf_metrics_histogram_proto_rawDescOnce.Do(func() {
		file_pbf_metrics_histogram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbf_metrics_histogram_proto_rawDesc), len(file_pbf_metrics_histogram_proto_rawDesc)))
	})
	return file_pbf_metrics_histogram_proto_rawDescData
}

var file_pbf_metrics_histogram_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbf_metrics_histogram_proto_goTypes = []any{
	(*HistogramI)(nil), // 0: metrics.HistogramI
	(*HistogramO)(nil), // 1: metrics.HistogramO
	(*Action)(nil),     // 2: metrics.Action
	(*Result)(nil),     // 3: metrics.Result
}
var file_pbf_metrics_histogram_proto_depIdxs = []int32{
	2, // 0: metrics.HistogramI.action:type_name -> metrics.Action
	3, // 1: metrics.HistogramO.result:type_name -> metrics.Result
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbf_metrics_histogram_proto_init() }
func file_pbf_metrics_histogram_proto_init() {
	if File_pbf_metrics_histogram_proto != nil {
		return
	}
	file_pbf_metrics_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbf_metrics_histogram_proto_rawDesc), len(file_pbf_metrics_histogram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbf_metrics_histogram_proto_goTypes,
		DependencyIndexes: file_pbf_metrics_histogram_proto_depIdxs,
		MessageInfos:      file_pbf_metrics_histogram_proto_msgTypes,
	}.Build()
	File_pbf_metrics_histogram_proto = out.File
	file_pbf_metrics_histogram_proto_goTypes = nil
	file_pbf_metrics_histogram_proto_depIdxs = nil
}
